server:
  port: 8300
spring:
  application:
    name: consumer-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
