server:
  port: 8500
  tomcat:
    max-threads: 10
spring:
  application:
    name: hystrix-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8100/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      circuit:
        
      execution:
        isolation:
          thread:
          #hystrix的超时时长
            timeoutInMilliseconds: 1000