server:
  port: 8400
spring:
  application:
    name: feign-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
    register-with-eureka: true
    fetch-registry: true
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000