server:
  port: 80
spring:
  application:
    name: zuul-service
#  cloud:
#    config:
#      profile: dev
#      discovery:
#        enabled: true
#        service-id: config-server
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/


zuul:
  routes:
    api-a: 
      path: /api-hello/*
      service-id: api-service
    api-b: 
      path: /api-consumer/*
      service-id: consumer-service
  retryable: true


ribbon:
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 2
  #ReadTimeout: 3000
  #ConnectTimeout: 3000
